export const options = {
  data: {
    'Aerobics, low intensity': null,
    'Aerobics, high intensity': null,
    'Aerobics, step': null,
    Badminton: null,
    'Ballet dancing': null,
    Baseball: null,
    Basketball: null,
    'Bicycling, easy (8.7mi/h or 14km/h)': null,
    'Bicycling, moderate (15mi/h - 24km/h)': null,
    'Bicycling, vigorous (20mi/h - 32km/h)': null,
    Bowling: null,
    Boxing: null,
    Calisthenics: null,
    Canoeing: null,
    Cheerleading: null,
    'Circuit training (squats, lunges, pushups, burpees, situps etc)': null,
    'Climbing, indoor/outdoor': null,
    Croquet: null,
    CrossFit: null,
    Dancing: null,
    'Elliptical trainer': null,
    Fencing: null,
    Fishing: null,
    'Football/soccer': null,
    'Gardening / yard work': null,
    'Golf (carrying clubs)': null,
    'Grocery shopping': null,
    Gymnastics: null,
    Handball: null,
    HIIT: null,
    'Hiking / orienteering': null,
    'Hockey, field and ice': null,
    'Horseback riding': null,
    Housework: null,
    'Ice skating': null,
    'In-line skating/Rollerblading': null,
    'Jumping rope (skipping), fast': null,
    'Jumping rope (skipping), moderate': null,
    Kayaking: null,
    'Kickboxing / MMA': null,
    Lacrosse: null,
    'Martial Arts': null,
    'Mowing lawn': null,
    Pilates: null,
    'Punching bag': null,
    'Raking lawn/leaves': null,
    Racquetball: null,
    Rowing: null,
    'Rowing machine': null,
    Rugby: null,
    'Running, 12min/mi = 7min/km': null,
    'Running, 10min/mi = 5.35min/km': null,
    'Running, 8min/mi = 4.28min/km': null,
    'Sailing, boat and board': null,
    'Shoveling snow': null,
    Skateboarding: null,
    'Skiing, light/moderate': null,
    'Skiing, cross-country': null,
    Sledding: null,
    'Snowboarding/snowshoeing': null,
    Snowmobiling: null,
    Softball: null,
    Spinning: null,
    Squash: null,
    'Stair climbing, machine': null,
    'Stair climbing, down stairs': null,
    'Stair climbing, up stairs': null,
    Surfing: null,
    'Swimming, butterfly': null,
    'Swimming, freestyle/breaststroke': null,
    'Swimming, treading/leisure': null,
    'Table tennis': null,
    'Tae Bo': null,
    'Tai Chi': null,
    Tennis: null,
    Trampoline: null,
    Volleyball: null,
    'Walking, stroll': null,
    'Walking, average': null,
    'Walking, power': null,
    'Washing a car': null,
    'Water aerobics': null,
    'Water polo': null,
    'Water skiing': null,
    'Weight lifting, light': null,
    'Weight lifting, heavy': null,
    Wrestling: null,
    Yoga: null,
  },
};
